name: 'Tests'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  Tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
        
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Run tests
      run: |
        cd LambdaCalculus/LambdaCalculusTests
        dotnet test -c release
